version: 2

build:
  # TODO: update to `latest` once supported
  # https://github.com/readthedocs/readthedocs.org/issues/8861
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# We can't use "all" because "htmlzip" format is broken for now
formats:
  - epub
  - pdf

python:
  install:
    - requirements: requirements-docs.txt
