# File: .readthedocs.yaml

version: 2

# Set the version of Python and other tools you might need
build:
  # TODO: update to `latest` once supported
  # https://github.com/readthedocs/readthedocs.org/issues/8861
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: all


# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements-docs.txt
