from .algebraic_optimization import AlgebraicOptimizationPass
from .assert_combiner import AssertCombinerPass
from .assert_elimination import AssertEliminationPass
from .assign_elimination import AssignElimination
from .branch_optimization import BranchOptimizationPass
from .cfg_normalization import CFGNormalization
from .common_subexpression_elimination import CSE
from .concretize_mem_loc import ConcretizeMemLocPass
from .dead_store_elimination import DeadStoreElimination
from .dft import DFTPass
from .fix_calloca import FixCalloca
from .fix_mem_locations import FixMemLocationsPass
from .float_allocas import FloatAllocas
from .function_inliner import FunctionInlinerPass
from .literals_codesize import ReduceLiteralsCodesize
from .load_elimination import LoadElimination
from .lower_dload import LowerDloadPass
from .make_ssa import MakeSSA
from .mem2var import Mem2Var
from .memmerging import MemMergePass
from .memory_copy_elision import MemoryCopyElisionPass
from .phi_elimination import PhiEliminationPass
from .remove_unused_variables import RemoveUnusedVariablesPass
from .revert_to_assert import RevertToAssert
from .sccp import SCCP
from .simplify_cfg import SimplifyCFGPass
from .single_use_expansion import SingleUseExpansion
from .tail_merge import TailMergePass
