name: Era compiler tester

# run the matter labs compiler test to integrate their test cases
# this is intended as a diagnostic / spot check to check that we
# haven't seriously broken the compiler. but, it is not intended as
# a requirement for merging since we may make changes to our IR
# which break the downstream backend (at which point, downstream needs
# to update, which we do not want to be blocked on).

on: [push, pull_request]

permissions:
  contents: read

env:
  ERA_HASH: 943fcc39d1173409fb4a3f53029b170fb7cb4e60
  PYTHON_VERSION: "3.12"

concurrency:
  # cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  era-compiler-tester:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        persist-credentials: false

    - name: Rust setup
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
      with:
        toolchain: nightly-2022-11-03

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: "pip"

    - name: Get cache
      id: get-cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          **/target
          **/target-llvm
          **/compiler_tester
          **/llvm
          **/era-compiler-tester
        key: ${{ runner.os }}-${{ env.ERA_HASH }}

    - name: Initialize repository and install dependencies
      if: steps.get-cache.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/matter-labs/era-compiler-tester.git
        cd era-compiler-tester
        git -c advice.detachedHead=false checkout --detach "$ERA_HASH"
        sed -i 's/ssh:\/\/git@/https:\/\//g' .gitmodules
        git submodule init
        git submodule update
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang-13 lld-13 parallel pkg-config lld
        cargo install compiler-llvm-builder
        zkevm-llvm clone && zkevm-llvm build
        cargo build --release

    - name: Save cache
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      if: steps.get-cache.outputs.cache-hit != 'true'
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          **/target
          **/target-llvm
          **/compiler_tester
          **/llvm
          **/era-compiler-tester
        key: ${{ runner.os }}-${{ env.ERA_HASH }}

    - name: Build Vyper
      run: |
        set -Eeuxo pipefail
        pip install .
        echo "VYPER_VERSION=$(vyper --version | cut -f1 -d'+')" >> $GITHUB_ENV

    - name: Install Vyper
      run: |
        mkdir era-compiler-tester/vyper-bin
        cp "$(which vyper)" "era-compiler-tester/vyper-bin/vyper-${VYPER_VERSION}"

    - name: Run tester (fast)
      # Run era tester with no LLVM optimizations
      continue-on-error: true
      if: ${{ github.ref != 'refs/heads/master' }}
      run: |
        cd era-compiler-tester
        cargo run --release --bin compiler-tester -- --path=tests/vyper/ --mode="M0B0 ${VYPER_VERSION}"

    - name: Run tester (slow)
      # Run era tester across the LLVM optimization matrix
      continue-on-error: true
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        cd era-compiler-tester
        cargo run --release --bin compiler-tester -- --path=tests/vyper/ --mode="M*B* ${VYPER_VERSION}"

    - name: Mark as success
      run: |
        exit 0
