# upload to pypi using the pypa publish action
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish to PyPI

on:
  release:
    types: [published]  # releases and pre-releases (release candidates)

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release

    steps:
    - uses: actions/checkout@v4
      with:
        # fetch unshallow so commit hash matches github release.
        # see https://github.com/vyperlang/vyper/blob/8f9a8cac49aafb3fbc9dde78f0f6125c390c32f0/.github/workflows/build.yml#L27-L32
        fetch-depth: 0

    # debug
    - name: Git shorthash
      run: git rev-parse --short HEAD

    - name: Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build
      run: python setup.py sdist bdist_wheel

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
